///////////////////////////////////////////////////////////////////////////////
///
/// \file   input.h
///
/// \brief  Subroutines for reading input file generated by SCI
///
/// \author Mingang Jin, Qingyan Chen
///         Purdue University
///         Jin56@purdue.edu, YanChen@purdue.edu
///         Wangda Zuo
///         University of Miami
///         W.Zuo@miami.edu
///
/// \date   04/02/2013
///
/// This file provides functions for reading the data from the file generated by
/// SCI, and the algoritm to indentifing the cell properties in the domain with 
/// the function \c mark_cell()
///
///////////////////////////////////////////////////////////////////////////////


int read_max(PARA_DATA *para, REAL **var);
int read_input(PARA_DATA *para, REAL **var, int **BINDEX);
void mark_cell(PARA_DATA *para, REAL **var, int **BINDEX);
